### PR TITLE
Use serverless

### PR DESCRIPTION
**Pull request by Priyanka328**

### CODE REVIEW

**Comment by m0rsch1** [comment]
Works for me.

**Comment by m0rsch1** [comment]
Improvements:
* When I change from e.g. 'Serverless' to 'Client' the window that the Client is not running always pops up even if the jsondb is running. I can add components afterwards.
* For 'Client' and 'MultiDBClient' there should be fields to select URL (and port etc.)
* For 'Serverless' we should be able to edit/change the path

**Comment by Priyanka328** [comment]
@m0rsch1 4525e8b6c46f3f6d8123efd847ff3813895998f8 commit should resolve the first .

**Comment by m0rsch1** [comment]
> @m0rsch1 [4525e8b](https://github.com/dfki-ric/xrock_gui_model/commit/4525e8b6c46f3f6d8123efd847ff3813895998f8) commit should resolve the first .

This has been fixed :)

**Comment by m0rsch1** [comment]
Actually, I would propose that no NEW features are added into this branch. Instead it should be merged asap. Otherwise it will turn into a neverending story.

**Comment by m0rsch1** [comment]
```
src/ModelWidget.cpp:333:17: error: ‘class bagel_gui::BagelGui’ has no member named ‘getCurrentTabView’; did you mean ‘bagel_gui::View* bagel_gui::BagelGui::currentTabView’? (not accessible from this context)
  333 |       bagelGui->getCurrentTabView()->setHasChanges(false); // everything was saved to db, view has no unsaved work.
      |                 ^~~~~~~~~~~~~~~~~
```

**Comment by m0rsch1** [comment]
> ```
> src/ModelWidget.cpp:333:17: error: ‘class bagel_gui::BagelGui’ has no member named ‘getCurrentTabView’; did you mean ‘bagel_gui::View* bagel_gui::BagelGui::currentTabView’? (not accessible from this context)
>   333 |       bagelGui->getCurrentTabView()->setHasChanges(false); // everything was saved to db, view has no unsaved work.
>       |                 ^~~~~~~~~~~~~~~~~
> ```

Fixed :)

**Comment by Priyanka328** [comment]
3908b0ba9a08d4ed4649f0f7e69feea091318f2f will fix the reload issue

**Pull request merged**
